Update for dash 3
app.run_server triggers a crash when running with Dash>2:

Traceback (most recent call last):
  File /tmp/tmp_smgb6f5/webviz_app.py, line 473, in <module>
    app.run_server(
    ^^^^^^^^^^^^^^
  File /data/venv/lib64/python3.12/site-packages/dash/_obsolete.py, line 22, in __getattr__
    raise err.exc(err.message)
dash.exceptions.ObsoleteAttributeException: app.run_server has been replaced by app.run